//! CLI command handlers for `mcp-gateway`.
//!
//! Each public function corresponds to a top-level `Command` variant and
//! returns an `ExitCode` so `main` can remain a thin dispatcher.

use std::process::ExitCode;
use std::sync::Arc;

use mcp_gateway::{
    capability::{
        AuthTemplate, CapabilityExecutor, CapabilityLoader, OpenApiConverter,
        parse_capability_file, validate_capability,
    },
    cli::{
        CapCommand, TlsCommand, ToolCommand,
        completion::{ShellTarget, generate_completion},
        invoke::{ToolCatalogue, build_completion_tool_names, execute_tool, resolve_args},
        output::{OutputFormat, print_tool_inspect, print_tool_list, print_tool_result},
    },
    discovery::AutoDiscovery,
    mtls::{CaParams, CertGenerator, LeafCertParams},
    registry::Registry,
};

// ── init ─────────────────────────────────────────────────────────────────────

/// Generate a starter gateway configuration file.
///
/// Writes a commented YAML configuration to `output`. When `with_examples` is
/// `true` three free-tier capability definitions are included so the user can
/// start experimenting immediately.
pub fn run_init_command(output: &std::path::Path, with_examples: bool) -> ExitCode {
    if output.exists() {
        eprintln!(
            "Error: {} already exists. Remove it first or choose a different path with --output.",
            output.display()
        );
        return ExitCode::FAILURE;
    }

    let config_content = build_init_config(with_examples);

    match std::fs::write(output, config_content) {
        Ok(()) => {
            print_init_success(output);
            ExitCode::SUCCESS
        }
        Err(e) => {
            eprintln!("Error: Failed to write {}: {e}", output.display());
            ExitCode::FAILURE
        }
    }
}

fn build_init_config(with_examples: bool) -> String {
    let examples_section = if with_examples {
        r#"
# Capabilities - direct REST API integration (no MCP server needed)
# These free capabilities work out of the box with zero API keys.
capabilities:
  enabled: true
  directories:
    - capabilities

# Example MCP backends (uncomment to enable)
# backends:
#   filesystem:
#     command: "npx -y @anthropic/mcp-server-filesystem /path/to/dir"
#     description: "File system access"
#   brave-search:
#     command: "npx -y @anthropic/mcp-server-brave-search"
#     description: "Web search via Brave"
#     env:
#       BRAVE_API_KEY: "${BRAVE_API_KEY}"
"#
    } else {
        r#"
# Capabilities - direct REST API integration
capabilities:
  enabled: true
  directories:
    - capabilities

# Add your MCP backends here:
# backends:
#   my-server:
#     command: "npx -y @my/mcp-server"
#     description: "My MCP server"
"#
    };

    format!(
        r#"# MCP Gateway Configuration
# ========================
# Generated by: mcp-gateway init
#
# Documentation: https://github.com/MikkoParkkola/mcp-gateway#readme

# Server settings
server:
  host: "127.0.0.1"
  port: 3000

# Meta-MCP mode - exposes 4 meta-tools for dynamic tool discovery
# Reduces context tokens by ~95% compared to loading all tools upfront
meta_mcp:
  enabled: true
  cache_tools: true
  cache_ttl: 300s
{examples_section}"#
    )
}

fn print_init_success(output: &std::path::Path) {
    println!("Created {}", output.display());
    println!();
    println!("Next steps:");
    println!("  1. Review and edit {}", output.display());
    println!("  2. Start the gateway:");
    println!("     mcp-gateway -c {}", output.display());
    println!("  3. Add to your MCP client (e.g. Claude Desktop):");
    println!("     {{");
    println!("       \"mcpServers\": {{");
    println!("         \"gateway\": {{");
    println!("           \"url\": \"http://127.0.0.1:3000/mcp\"");
    println!("         }}");
    println!("       }}");
    println!("     }}");
}

// ── tls ──────────────────────────────────────────────────────────────────────

/// Run `mcp-gateway tls` subcommands.
#[allow(clippy::too_many_lines)]
pub fn run_tls_command(cmd: TlsCommand) -> ExitCode {
    match cmd {
        TlsCommand::InitCa { cn, validity_days, out } => tls_init_ca(&cn, validity_days, &out),
        TlsCommand::IssueServer {
            ca_cert, ca_key, cn, san_dns, validity_days, out,
        } => tls_issue_server(&ca_cert, &ca_key, &cn, &san_dns, validity_days, &out),
        TlsCommand::IssueClient {
            ca_cert, ca_key, cn, ou, spiffe_uri, validity_days, out,
        } => tls_issue_client(&ca_cert, &ca_key, &cn, ou.as_deref(), spiffe_uri, validity_days, &out),
    }
}

fn tls_init_ca(cn: &str, validity_days: u32, out: &std::path::Path) -> ExitCode {
    println!("Generating Root CA: {cn}");
    let params = CaParams { cn, validity_days };
    match CertGenerator::init_ca(&params) {
        Ok(cert) => {
            if let Err(e) = CertGenerator::write_to_dir(&cert, out, "ca") {
                eprintln!("Error: Failed to write CA files: {e}");
                return ExitCode::FAILURE;
            }
            println!("  CA cert: {}", out.join("ca.crt").display());
            println!("  CA key:  {}", out.join("ca.key").display());
            println!();
            println!("Keep the CA key offline or in a vault.");
            println!("Add to gateway.yaml:");
            println!("  mtls:");
            println!("    ca_cert: \"{}\"", out.join("ca.crt").display());
            ExitCode::SUCCESS
        }
        Err(e) => {
            eprintln!("Error: CA generation failed: {e}");
            ExitCode::FAILURE
        }
    }
}

fn tls_issue_server(
    ca_cert: &std::path::Path,
    ca_key: &std::path::Path,
    cn: &str,
    san_dns: &str,
    validity_days: u32,
    out: &std::path::Path,
) -> ExitCode {
    println!("Issuing server certificate for: {cn}");
    let (ca_cert_pem, ca_key_pem) = match read_ca_files(ca_cert, ca_key) {
        Ok(pair) => pair,
        Err(code) => return code,
    };
    let sans: Vec<String> = san_dns
        .split(',')
        .filter(|s| !s.is_empty())
        .map(str::to_owned)
        .collect();
    let params = LeafCertParams {
        cn,
        ou: None,
        san_dns: sans,
        san_uris: vec![],
        validity_days,
    };
    match CertGenerator::issue_leaf(&params, &ca_cert_pem, &ca_key_pem) {
        Ok(cert) => {
            if let Err(e) = CertGenerator::write_to_dir(&cert, out, "server") {
                eprintln!("Error: Failed to write server cert files: {e}");
                return ExitCode::FAILURE;
            }
            println!("  Cert: {}", out.join("server.crt").display());
            println!("  Key:  {}", out.join("server.key").display());
            println!();
            println!("Add to gateway.yaml:");
            println!("  mtls:");
            println!("    enabled: true");
            println!("    server_cert: \"{}\"", out.join("server.crt").display());
            println!("    server_key:  \"{}\"", out.join("server.key").display());
            ExitCode::SUCCESS
        }
        Err(e) => {
            eprintln!("Error: Server cert generation failed: {e}");
            ExitCode::FAILURE
        }
    }
}

fn tls_issue_client(
    ca_cert: &std::path::Path,
    ca_key: &std::path::Path,
    cn: &str,
    ou: Option<&str>,
    spiffe_uri: Option<String>,
    validity_days: u32,
    out: &std::path::Path,
) -> ExitCode {
    println!("Issuing client certificate for: {cn}");
    let (ca_cert_pem, ca_key_pem) = match read_ca_files(ca_cert, ca_key) {
        Ok(pair) => pair,
        Err(code) => return code,
    };
    let san_uris = spiffe_uri.map(|u| vec![u]).unwrap_or_default();
    let params = LeafCertParams { cn, ou, san_dns: vec![], san_uris, validity_days };
    let stem = cn.replace(['/', ' '], "-");
    match CertGenerator::issue_leaf(&params, &ca_cert_pem, &ca_key_pem) {
        Ok(cert) => {
            if let Err(e) = CertGenerator::write_to_dir(&cert, out, &stem) {
                eprintln!("Error: Failed to write client cert files: {e}");
                return ExitCode::FAILURE;
            }
            println!("  Cert: {}", out.join(format!("{stem}.crt")).display());
            println!("  Key:  {}", out.join(format!("{stem}.key")).display());
            println!();
            println!("Configure the agent:");
            println!(
                "  export MCP_GATEWAY_CLIENT_CERT={}",
                out.join(format!("{stem}.crt")).display()
            );
            println!(
                "  export MCP_GATEWAY_CLIENT_KEY={}",
                out.join(format!("{stem}.key")).display()
            );
            ExitCode::SUCCESS
        }
        Err(e) => {
            eprintln!("Error: Client cert generation failed: {e}");
            ExitCode::FAILURE
        }
    }
}

/// Read CA cert and key PEM files, returning early with `FAILURE` on I/O errors.
fn read_ca_files(
    ca_cert: &std::path::Path,
    ca_key: &std::path::Path,
) -> Result<(String, String), ExitCode> {
    let cert = std::fs::read_to_string(ca_cert).map_err(|e| {
        eprintln!("Error: Cannot read CA cert '{}': {e}", ca_cert.display());
        ExitCode::FAILURE
    })?;
    let key = std::fs::read_to_string(ca_key).map_err(|e| {
        eprintln!("Error: Cannot read CA key '{}': {e}", ca_key.display());
        ExitCode::FAILURE
    })?;
    Ok((cert, key))
}

// ── tool ─────────────────────────────────────────────────────────────────────

/// Run `mcp-gateway tool` subcommands (CLI bridge for direct tool invocation).
pub async fn run_tool_command(cmd: ToolCommand) -> ExitCode {
    match cmd {
        ToolCommand::List { capabilities, format } => tool_list(capabilities, format).await,
        ToolCommand::Inspect { tool, capabilities, format } => {
            tool_inspect(tool, capabilities, format).await
        }
        ToolCommand::Invoke { tool, capabilities, args, kv_args, format } => {
            tool_invoke(tool, capabilities, args, kv_args, format).await
        }
        ToolCommand::Completions { shell, capabilities } => {
            tool_completions(shell, capabilities).await
        }
    }
}

async fn tool_list(capabilities: std::path::PathBuf, format: OutputFormat) -> ExitCode {
    let dir = capabilities.to_string_lossy();
    match ToolCatalogue::load(&dir).await {
        Ok(cat) => {
            print_tool_list(&cat.list_entries(), format);
            ExitCode::SUCCESS
        }
        Err(e) => {
            eprintln!("Error: Failed to load capabilities from '{dir}': {e}");
            ExitCode::FAILURE
        }
    }
}

async fn tool_inspect(
    tool: String,
    capabilities: std::path::PathBuf,
    format: OutputFormat,
) -> ExitCode {
    let dir = capabilities.to_string_lossy();
    match ToolCatalogue::load(&dir).await {
        Ok(cat) => {
            if let Some(cap) = cat.find(&tool) {
                print_tool_inspect(&cap.name, &cap.description, &cap.schema.input, format);
                ExitCode::SUCCESS
            } else {
                eprintln!("Error: Tool '{tool}' not found. Run 'tool list' to see available tools.");
                ExitCode::FAILURE
            }
        }
        Err(e) => {
            eprintln!("Error: Failed to load capabilities from '{dir}': {e}");
            ExitCode::FAILURE
        }
    }
}

async fn tool_invoke(
    tool: String,
    capabilities: std::path::PathBuf,
    args: Option<String>,
    kv_args: Vec<String>,
    format: OutputFormat,
) -> ExitCode {
    let dir = capabilities.to_string_lossy();
    let catalogue = match ToolCatalogue::load(&dir).await {
        Ok(c) => c,
        Err(e) => {
            eprintln!("Error: Failed to load capabilities from '{dir}': {e}");
            return ExitCode::FAILURE;
        }
    };
    let resolved = match resolve_args(args.as_deref(), &kv_args, true) {
        Ok(v) => v,
        Err(e) => {
            eprintln!("Error: {e}");
            return ExitCode::FAILURE;
        }
    };
    match execute_tool(&catalogue, &tool, resolved).await {
        Ok(result) => {
            print_tool_result(&result, format);
            ExitCode::SUCCESS
        }
        Err(e) => {
            eprintln!("Error: {e}");
            ExitCode::FAILURE
        }
    }
}

async fn tool_completions(shell: clap_complete::Shell, capabilities: std::path::PathBuf) -> ExitCode {
    let dir = capabilities.to_string_lossy();
    let tool_names = build_completion_tool_names(&dir).await;
    let target = ShellTarget::from_shell(shell).unwrap_or(ShellTarget::Bash);
    let script = generate_completion(target, &tool_names);
    print!("{script}");
    ExitCode::SUCCESS
}

// ── stats ─────────────────────────────────────────────────────────────────────

/// Run the `stats` command against a running gateway.
pub async fn run_stats_command(url: &str, price: f64) -> ExitCode {
    use serde_json::json;

    let client = reqwest::Client::new();
    let request_body = json!({
        "jsonrpc": "2.0",
        "id": 1,
        "method": "tools/call",
        "params": {
            "name": "gateway_get_stats",
            "arguments": { "price_per_million": price }
        }
    });

    let endpoint = format!("{}/mcp", url.trim_end_matches('/'));

    match client.post(&endpoint).json(&request_body).send().await {
        Ok(response) => handle_stats_response(response, &endpoint).await,
        Err(e) => {
            eprintln!("❌ Failed to connect to gateway: {e}");
            eprintln!("   Make sure the gateway is running at {url}");
            ExitCode::FAILURE
        }
    }
}

async fn handle_stats_response(response: reqwest::Response, url: &str) -> ExitCode {
    if !response.status().is_success() {
        eprintln!("❌ Gateway returned error: {}", response.status());
        return ExitCode::FAILURE;
    }
    match response.json::<serde_json::Value>().await {
        Ok(body) => print_stats_body(&body, url),
        Err(e) => {
            eprintln!("❌ Failed to parse response: {e}");
            ExitCode::FAILURE
        }
    }
}

fn print_stats_body(body: &serde_json::Value, _url: &str) -> ExitCode {
    if let Some(text) = extract_stats_text(body) {
        if let Ok(stats) = serde_json::from_str::<serde_json::Value>(text) {
            println!("📊 Gateway Statistics\n");
            println!("Invocations:       {}", stats["invocations"]);
            println!("Cache Hits:        {}", stats["cache_hits"]);
            println!("Cache Hit Rate:    {}", stats["cache_hit_rate"]);
            println!("Tools Discovered:  {}", stats["tools_discovered"]);
            println!("Tools Available:   {}", stats["tools_available"]);
            println!("Tokens Saved:      {}", stats["tokens_saved"].as_u64().unwrap_or(0));
            println!("Estimated Savings: {}", stats["estimated_savings_usd"]);
            print_top_tools(&stats);
            return ExitCode::SUCCESS;
        }
    }
    if let Some(error) = body.get("error") {
        eprintln!(
            "❌ Error: {}",
            error.get("message").and_then(|v| v.as_str()).unwrap_or("Unknown")
        );
        return ExitCode::FAILURE;
    }
    eprintln!("❌ Unexpected response format");
    ExitCode::FAILURE
}

fn extract_stats_text(body: &serde_json::Value) -> Option<&str> {
    body.get("result")?
        .get("content")?
        .as_array()?
        .first()?
        .get("text")?
        .as_str()
}

fn print_top_tools(stats: &serde_json::Value) {
    if let Some(top_tools) = stats["top_tools"].as_array() {
        if !top_tools.is_empty() {
            println!("\n🏆 Top Tools:");
            for tool in top_tools {
                println!(
                    "  • {}:{} - {} calls",
                    tool["server"].as_str().unwrap_or(""),
                    tool["tool"].as_str().unwrap_or(""),
                    tool["count"]
                );
            }
        }
    }
}

// ── cap ───────────────────────────────────────────────────────────────────────

/// Run a `cap` subcommand (validate, list, import, test, discover, install, search, …).
#[allow(clippy::too_many_lines)]
pub async fn run_cap_command(cmd: CapCommand) -> ExitCode {
    match cmd {
        CapCommand::Validate { file } => cap_validate(file).await,
        CapCommand::List { directory } => cap_list(directory).await,
        CapCommand::Import { spec, output, prefix, auth_key } => {
            cap_import(spec, output, prefix, auth_key).await
        }
        CapCommand::Test { file, args } => cap_test(file, args).await,
        CapCommand::Discover { format, write_config, config_path } => {
            cap_discover(format, write_config, config_path).await
        }
        CapCommand::Install { name, from_github, repo, branch, output } => {
            cap_install(name, from_github, repo, branch, output).await
        }
        CapCommand::Search { query, capabilities } => cap_search(query, capabilities).await,
        CapCommand::RegistryList { capabilities } => cap_registry_list(capabilities).await,
    }
}

async fn cap_validate(file: std::path::PathBuf) -> ExitCode {
    match parse_capability_file(&file).await {
        Ok(cap) => {
            if let Err(e) = validate_capability(&cap) {
                eprintln!("❌ Validation failed: {e}");
                return ExitCode::FAILURE;
            }
            println!("✅ {} - valid", cap.name);
            if !cap.description.is_empty() {
                println!("   {}", cap.description);
            }
            if let Some(provider) = cap.primary_provider() {
                println!("   Provider: {} ({})", provider.service, provider.config.method);
                println!("   URL: {}{}", provider.config.base_url, provider.config.path);
            }
            if cap.auth.required {
                println!("   Auth: {} ({})", cap.auth.auth_type, cap.auth.key);
            }
            ExitCode::SUCCESS
        }
        Err(e) => {
            eprintln!("❌ Failed to parse: {e}");
            ExitCode::FAILURE
        }
    }
}

async fn cap_list(directory: std::path::PathBuf) -> ExitCode {
    let path = directory.to_string_lossy();
    match CapabilityLoader::load_directory(&path).await {
        Ok(caps) => {
            if caps.is_empty() {
                println!("No capabilities found in {path}");
            } else {
                println!("Found {} capabilities in {}:\n", caps.len(), path);
                for cap in caps {
                    let auth_info = if cap.auth.required {
                        format!(" [{}]", cap.auth.auth_type)
                    } else {
                        String::new()
                    };
                    println!("  {} - {}{}", cap.name, cap.description, auth_info);
                }
            }
            ExitCode::SUCCESS
        }
        Err(e) => {
            eprintln!("❌ Failed to load: {e}");
            ExitCode::FAILURE
        }
    }
}

async fn cap_import(
    spec: std::path::PathBuf,
    output: std::path::PathBuf,
    prefix: Option<String>,
    auth_key: Option<String>,
) -> ExitCode {
    let mut converter = OpenApiConverter::new();
    if let Some(p) = prefix {
        converter = converter.with_prefix(&p);
    }
    if let Some(key) = auth_key {
        converter = converter.with_default_auth(AuthTemplate {
            auth_type: "bearer".to_string(),
            key,
            description: "API authentication".to_string(),
        });
    }
    let spec_path = spec.to_string_lossy();
    match converter.convert_file(&spec_path) {
        Ok(caps) => {
            let out_path = output.to_string_lossy();
            println!("Generated {} capabilities from {}\n", caps.len(), spec_path);
            for cap in caps {
                if let Err(e) = cap.write_to_file(&out_path) {
                    eprintln!("❌ Failed to write {}: {e}", cap.name);
                } else {
                    println!("  ✅ {}.yaml", cap.name);
                }
            }
            println!("\nCapabilities written to {out_path}/");
            ExitCode::SUCCESS
        }
        Err(e) => {
            eprintln!("❌ Failed to convert: {e}");
            ExitCode::FAILURE
        }
    }
}

async fn cap_test(file: std::path::PathBuf, args: String) -> ExitCode {
    let cap = match parse_capability_file(&file).await {
        Ok(c) => c,
        Err(e) => {
            eprintln!("❌ Failed to parse capability: {e}");
            return ExitCode::FAILURE;
        }
    };
    let params: serde_json::Value = match serde_json::from_str(&args) {
        Ok(v) => v,
        Err(e) => {
            eprintln!("❌ Invalid JSON arguments: {e}");
            return ExitCode::FAILURE;
        }
    };
    println!("Testing capability: {}", cap.name);
    println!("Arguments: {}", serde_json::to_string_pretty(&params).unwrap_or_default());
    println!();
    let executor = Arc::new(CapabilityExecutor::new());
    match executor.execute(&cap, params).await {
        Ok(result) => {
            println!("✅ Success:\n");
            println!("{}", serde_json::to_string_pretty(&result).unwrap_or_default());
            ExitCode::SUCCESS
        }
        Err(e) => {
            eprintln!("❌ Execution failed: {e}");
            ExitCode::FAILURE
        }
    }
}

async fn cap_discover(
    format: String,
    write_config: bool,
    config_path: Option<std::path::PathBuf>,
) -> ExitCode {
    let discovery = AutoDiscovery::new();
    println!("🔍 Discovering MCP servers...\n");
    match discovery.discover_all().await {
        Ok(servers) => {
            if servers.is_empty() {
                print_discover_empty();
                return ExitCode::SUCCESS;
            }
            print_discovered_servers(&servers, &format);
            if write_config {
                println!("\n📝 Writing discovered servers to config...");
                match crate::write_discovered_to_config(&servers, config_path.as_deref()) {
                    Ok(path) => {
                        println!("✅ Config written to {}", path.display());
                        println!(
                            "\nTo use discovered servers, start gateway with: mcp-gateway -c {}",
                            path.display()
                        );
                    }
                    Err(e) => {
                        eprintln!("❌ Failed to write config: {e}");
                        return ExitCode::FAILURE;
                    }
                }
            } else {
                println!("\n💡 To add these servers to your gateway config, run:");
                println!("   mcp-gateway cap discover --write-config");
            }
            ExitCode::SUCCESS
        }
        Err(e) => {
            eprintln!("❌ Discovery failed: {e}");
            ExitCode::FAILURE
        }
    }
}

fn print_discover_empty() {
    println!("No MCP servers found.");
    println!("\nSearched locations:");
    println!("  • Claude Desktop config");
    println!("  • VS Code/Cursor MCP configs");
    println!("  • Windsurf config");
    println!("  • ~/.config/mcp/*.json");
    println!("  • Running processes (pieces, surreal, etc.)");
    println!("  • Environment variables (MCP_SERVER_*_URL)");
}

fn print_discovered_servers(servers: &[mcp_gateway::discovery::DiscoveredServer], format: &str) {
    match format {
        "json" => println!("{}", serde_json::to_string_pretty(servers).unwrap_or_default()),
        "yaml" => println!("{}", serde_yaml::to_string(servers).unwrap_or_default()),
        _ => {
            println!("Discovered {} MCP server(s):\n", servers.len());
            for server in servers {
                print_server_entry(server);
            }
        }
    }
}

fn print_server_entry(server: &mcp_gateway::discovery::DiscoveredServer) {
    println!("📦 {}", server.name);
    println!("   Description: {}", server.description);
    println!("   Source: {:?}", server.source);
    match &server.transport {
        mcp_gateway::config::TransportConfig::Stdio { command, .. } => {
            println!("   Transport: stdio");
            println!("   Command: {command}");
        }
        mcp_gateway::config::TransportConfig::Http { http_url, .. } => {
            println!("   Transport: http");
            println!("   URL: {http_url}");
        }
    }
    if let Some(ref path) = server.metadata.config_path {
        println!("   Config: {}", path.display());
    }
    if let Some(pid) = server.metadata.pid {
        println!("   PID: {pid}");
    }
    println!();
}

async fn cap_install(
    name: String,
    from_github: bool,
    repo: String,
    branch: String,
    output: std::path::PathBuf,
) -> ExitCode {
    if from_github {
        println!("📦 Installing {name} from GitHub ({repo})...");
        let registry = Registry::new(&output);
        match registry.install_from_github(&name, &repo, &branch).await {
            Ok(path) => {
                println!("✅ Installed to {}", path.display());
                ExitCode::SUCCESS
            }
            Err(e) => {
                eprintln!("❌ Installation failed: {e}");
                ExitCode::FAILURE
            }
        }
    } else {
        println!("ℹ️  All capabilities are already available in the capabilities directory.");
        println!("   Use 'cap list' to see available capabilities.");
        ExitCode::SUCCESS
    }
}

async fn cap_search(query: String, capabilities: std::path::PathBuf) -> ExitCode {
    let reg = Registry::new(&capabilities);
    match reg.build_index().await {
        Ok(index) => {
            let results = index.search(&query);
            if results.is_empty() {
                println!("No capabilities found matching '{query}'");
            } else {
                println!("Found {} capability(ies) matching '{query}':\n", results.len());
                for entry in results {
                    let auth = if entry.requires_key { " 🔑" } else { "" };
                    println!("  {} - {}{}", entry.name, entry.description, auth);
                    if !entry.tags.is_empty() {
                        println!("    Tags: {}", entry.tags.join(", "));
                    }
                    println!();
                }
                println!("All capabilities are already available in the capabilities directory.");
            }
            ExitCode::SUCCESS
        }
        Err(e) => {
            eprintln!("❌ Failed to build registry index: {e}");
            ExitCode::FAILURE
        }
    }
}

async fn cap_registry_list(capabilities: std::path::PathBuf) -> ExitCode {
    let reg = Registry::new(&capabilities);
    match reg.build_index().await {
        Ok(index) => {
            println!("Available capabilities ({}):\n", index.capabilities.len());
            for entry in &index.capabilities {
                let auth = if entry.requires_key { " 🔑" } else { "" };
                println!("  {} - {}{}", entry.name, entry.description, auth);
                if !entry.tags.is_empty() {
                    println!("    Tags: {}", entry.tags.join(", "));
                }
                println!();
            }
            println!("All capabilities are available in the capabilities directory.");
            ExitCode::SUCCESS
        }
        Err(e) => {
            eprintln!("❌ Failed to build registry index: {e}");
            ExitCode::FAILURE
        }
    }
}
